//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QBPOSModel", "FK_InventoryAdjustmentInventoryAdjustmentItem", "InventoryAdjustment", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(QuickBooks.InventoryAdjustment), "InventoryAdjustmentItem", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuickBooks.InventoryAdjustmentItem), true)]
[assembly: EdmRelationshipAttribute("QBPOSModel", "FK_SalesReceiptSalesReceiptDetails", "SalesReceipt", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(QuickBooks.SalesReceipt), "SalesReceiptDetail", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(QuickBooks.SalesReceiptDetail), true)]

#endregion

namespace QuickBooks
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QBPOSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QBPOSEntities object using the connection string found in the 'QBPOSEntities' section of the application configuration file.
        /// </summary>
        public QBPOSEntities() : base("name=QBPOSEntities", "QBPOSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QBPOSEntities object.
        /// </summary>
        public QBPOSEntities(string connectionString) : base(connectionString, "QBPOSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QBPOSEntities object.
        /// </summary>
        public QBPOSEntities(EntityConnection connection) : base(connection, "QBPOSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InventoryAdjustmentItem> InventoryAdjustmentItems
        {
            get
            {
                if ((_InventoryAdjustmentItems == null))
                {
                    _InventoryAdjustmentItems = base.CreateObjectSet<InventoryAdjustmentItem>("InventoryAdjustmentItems");
                }
                return _InventoryAdjustmentItems;
            }
        }
        private ObjectSet<InventoryAdjustmentItem> _InventoryAdjustmentItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InventoryAdjustment> InventoryAdjustments
        {
            get
            {
                if ((_InventoryAdjustments == null))
                {
                    _InventoryAdjustments = base.CreateObjectSet<InventoryAdjustment>("InventoryAdjustments");
                }
                return _InventoryAdjustments;
            }
        }
        private ObjectSet<InventoryAdjustment> _InventoryAdjustments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InventoryItem> InventoryItems
        {
            get
            {
                if ((_InventoryItems == null))
                {
                    _InventoryItems = base.CreateObjectSet<InventoryItem>("InventoryItems");
                }
                return _InventoryItems;
            }
        }
        private ObjectSet<InventoryItem> _InventoryItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SalesReceiptDetail> SalesReceiptDetails
        {
            get
            {
                if ((_SalesReceiptDetails == null))
                {
                    _SalesReceiptDetails = base.CreateObjectSet<SalesReceiptDetail>("SalesReceiptDetails");
                }
                return _SalesReceiptDetails;
            }
        }
        private ObjectSet<SalesReceiptDetail> _SalesReceiptDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SalesReceipt> SalesReceipts
        {
            get
            {
                if ((_SalesReceipts == null))
                {
                    _SalesReceipts = base.CreateObjectSet<SalesReceipt>("SalesReceipts");
                }
                return _SalesReceipts;
            }
        }
        private ObjectSet<SalesReceipt> _SalesReceipts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InventoryAdjustmentItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInventoryAdjustmentItems(InventoryAdjustmentItem inventoryAdjustmentItem)
        {
            base.AddObject("InventoryAdjustmentItems", inventoryAdjustmentItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InventoryAdjustments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInventoryAdjustments(InventoryAdjustment inventoryAdjustment)
        {
            base.AddObject("InventoryAdjustments", inventoryAdjustment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InventoryItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInventoryItems(InventoryItem inventoryItem)
        {
            base.AddObject("InventoryItems", inventoryItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SalesReceiptDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSalesReceiptDetails(SalesReceiptDetail salesReceiptDetail)
        {
            base.AddObject("SalesReceiptDetails", salesReceiptDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SalesReceipts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSalesReceipts(SalesReceipt salesReceipt)
        {
            base.AddObject("SalesReceipts", salesReceipt);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QBPOSModel", Name="InventoryAdjustment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InventoryAdjustment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InventoryAdjustment object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="txnDate">Initial value of the TxnDate property.</param>
        /// <param name="adjustmentNumber">Initial value of the AdjustmentNumber property.</param>
        /// <param name="adjustmentSource">Initial value of the AdjustmentSource property.</param>
        /// <param name="txnID">Initial value of the TxnID property.</param>
        public static InventoryAdjustment CreateInventoryAdjustment(global::System.Int32 id, global::System.DateTime txnDate, global::System.String adjustmentNumber, global::System.String adjustmentSource, global::System.String txnID)
        {
            InventoryAdjustment inventoryAdjustment = new InventoryAdjustment();
            inventoryAdjustment.Id = id;
            inventoryAdjustment.TxnDate = txnDate;
            inventoryAdjustment.AdjustmentNumber = adjustmentNumber;
            inventoryAdjustment.AdjustmentSource = adjustmentSource;
            inventoryAdjustment.TxnID = txnID;
            return inventoryAdjustment;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TxnDate
        {
            get
            {
                return _TxnDate;
            }
            set
            {
                OnTxnDateChanging(value);
                ReportPropertyChanging("TxnDate");
                _TxnDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TxnDate");
                OnTxnDateChanged();
            }
        }
        private global::System.DateTime _TxnDate;
        partial void OnTxnDateChanging(global::System.DateTime value);
        partial void OnTxnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AdjustmentNumber
        {
            get
            {
                return _AdjustmentNumber;
            }
            set
            {
                OnAdjustmentNumberChanging(value);
                ReportPropertyChanging("AdjustmentNumber");
                _AdjustmentNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AdjustmentNumber");
                OnAdjustmentNumberChanged();
            }
        }
        private global::System.String _AdjustmentNumber;
        partial void OnAdjustmentNumberChanging(global::System.String value);
        partial void OnAdjustmentNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AdjustmentSource
        {
            get
            {
                return _AdjustmentSource;
            }
            set
            {
                OnAdjustmentSourceChanging(value);
                ReportPropertyChanging("AdjustmentSource");
                _AdjustmentSource = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AdjustmentSource");
                OnAdjustmentSourceChanged();
            }
        }
        private global::System.String _AdjustmentSource;
        partial void OnAdjustmentSourceChanging(global::System.String value);
        partial void OnAdjustmentSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TxnID
        {
            get
            {
                return _TxnID;
            }
            set
            {
                OnTxnIDChanging(value);
                ReportPropertyChanging("TxnID");
                _TxnID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TxnID");
                OnTxnIDChanged();
            }
        }
        private global::System.String _TxnID;
        partial void OnTxnIDChanging(global::System.String value);
        partial void OnTxnIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QBPOSModel", "FK_InventoryAdjustmentInventoryAdjustmentItem", "InventoryAdjustmentItem")]
        public EntityCollection<InventoryAdjustmentItem> InventoryAdjustmentItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InventoryAdjustmentItem>("QBPOSModel.FK_InventoryAdjustmentInventoryAdjustmentItem", "InventoryAdjustmentItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InventoryAdjustmentItem>("QBPOSModel.FK_InventoryAdjustmentInventoryAdjustmentItem", "InventoryAdjustmentItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QBPOSModel", Name="InventoryAdjustmentItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InventoryAdjustmentItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InventoryAdjustmentItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="itemListID">Initial value of the ItemListID property.</param>
        /// <param name="newQuantity">Initial value of the NewQuantity property.</param>
        /// <param name="oldQuantity">Initial value of the OldQuantity property.</param>
        /// <param name="quantityDifference">Initial value of the QuantityDifference property.</param>
        /// <param name="inventoryAdjustmentId">Initial value of the InventoryAdjustmentId property.</param>
        public static InventoryAdjustmentItem CreateInventoryAdjustmentItem(global::System.Int32 id, global::System.String itemListID, global::System.Decimal newQuantity, global::System.Decimal oldQuantity, global::System.Decimal quantityDifference, global::System.Int32 inventoryAdjustmentId)
        {
            InventoryAdjustmentItem inventoryAdjustmentItem = new InventoryAdjustmentItem();
            inventoryAdjustmentItem.Id = id;
            inventoryAdjustmentItem.ItemListID = itemListID;
            inventoryAdjustmentItem.NewQuantity = newQuantity;
            inventoryAdjustmentItem.OldQuantity = oldQuantity;
            inventoryAdjustmentItem.QuantityDifference = quantityDifference;
            inventoryAdjustmentItem.InventoryAdjustmentId = inventoryAdjustmentId;
            return inventoryAdjustmentItem;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemListID
        {
            get
            {
                return _ItemListID;
            }
            set
            {
                OnItemListIDChanging(value);
                ReportPropertyChanging("ItemListID");
                _ItemListID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemListID");
                OnItemListIDChanged();
            }
        }
        private global::System.String _ItemListID;
        partial void OnItemListIDChanging(global::System.String value);
        partial void OnItemListIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NewQuantity
        {
            get
            {
                return _NewQuantity;
            }
            set
            {
                OnNewQuantityChanging(value);
                ReportPropertyChanging("NewQuantity");
                _NewQuantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NewQuantity");
                OnNewQuantityChanged();
            }
        }
        private global::System.Decimal _NewQuantity;
        partial void OnNewQuantityChanging(global::System.Decimal value);
        partial void OnNewQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal OldQuantity
        {
            get
            {
                return _OldQuantity;
            }
            set
            {
                OnOldQuantityChanging(value);
                ReportPropertyChanging("OldQuantity");
                _OldQuantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OldQuantity");
                OnOldQuantityChanged();
            }
        }
        private global::System.Decimal _OldQuantity;
        partial void OnOldQuantityChanging(global::System.Decimal value);
        partial void OnOldQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal QuantityDifference
        {
            get
            {
                return _QuantityDifference;
            }
            set
            {
                OnQuantityDifferenceChanging(value);
                ReportPropertyChanging("QuantityDifference");
                _QuantityDifference = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuantityDifference");
                OnQuantityDifferenceChanged();
            }
        }
        private global::System.Decimal _QuantityDifference;
        partial void OnQuantityDifferenceChanging(global::System.Decimal value);
        partial void OnQuantityDifferenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InventoryAdjustmentId
        {
            get
            {
                return _InventoryAdjustmentId;
            }
            set
            {
                OnInventoryAdjustmentIdChanging(value);
                ReportPropertyChanging("InventoryAdjustmentId");
                _InventoryAdjustmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InventoryAdjustmentId");
                OnInventoryAdjustmentIdChanged();
            }
        }
        private global::System.Int32 _InventoryAdjustmentId;
        partial void OnInventoryAdjustmentIdChanging(global::System.Int32 value);
        partial void OnInventoryAdjustmentIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QBPOSModel", "FK_InventoryAdjustmentInventoryAdjustmentItem", "InventoryAdjustment")]
        public InventoryAdjustment InventoryAdjustment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InventoryAdjustment>("QBPOSModel.FK_InventoryAdjustmentInventoryAdjustmentItem", "InventoryAdjustment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InventoryAdjustment>("QBPOSModel.FK_InventoryAdjustmentInventoryAdjustmentItem", "InventoryAdjustment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<InventoryAdjustment> InventoryAdjustmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InventoryAdjustment>("QBPOSModel.FK_InventoryAdjustmentInventoryAdjustmentItem", "InventoryAdjustment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<InventoryAdjustment>("QBPOSModel.FK_InventoryAdjustmentInventoryAdjustmentItem", "InventoryAdjustment", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QBPOSModel", Name="InventoryItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InventoryItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InventoryItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="listID">Initial value of the ListID property.</param>
        /// <param name="itemNumber">Initial value of the ItemNumber property.</param>
        public static InventoryItem CreateInventoryItem(global::System.Int32 id, global::System.String listID, global::System.Int32 itemNumber)
        {
            InventoryItem inventoryItem = new InventoryItem();
            inventoryItem.Id = id;
            inventoryItem.ListID = listID;
            inventoryItem.ItemNumber = itemNumber;
            return inventoryItem;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ListID
        {
            get
            {
                return _ListID;
            }
            set
            {
                OnListIDChanging(value);
                ReportPropertyChanging("ListID");
                _ListID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ListID");
                OnListIDChanged();
            }
        }
        private global::System.String _ListID;
        partial void OnListIDChanging(global::System.String value);
        partial void OnListIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Attribute
        {
            get
            {
                return _Attribute;
            }
            set
            {
                OnAttributeChanging(value);
                ReportPropertyChanging("Attribute");
                _Attribute = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Attribute");
                OnAttributeChanged();
            }
        }
        private global::System.String _Attribute;
        partial void OnAttributeChanging(global::System.String value);
        partial void OnAttributeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemDesc1
        {
            get
            {
                return _ItemDesc1;
            }
            set
            {
                OnItemDesc1Changing(value);
                ReportPropertyChanging("ItemDesc1");
                _ItemDesc1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemDesc1");
                OnItemDesc1Changed();
            }
        }
        private global::System.String _ItemDesc1;
        partial void OnItemDesc1Changing(global::System.String value);
        partial void OnItemDesc1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemDesc2
        {
            get
            {
                return _ItemDesc2;
            }
            set
            {
                OnItemDesc2Changing(value);
                ReportPropertyChanging("ItemDesc2");
                _ItemDesc2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemDesc2");
                OnItemDesc2Changed();
            }
        }
        private global::System.String _ItemDesc2;
        partial void OnItemDesc2Changing(global::System.String value);
        partial void OnItemDesc2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ALU
        {
            get
            {
                return _ALU;
            }
            set
            {
                OnALUChanging(value);
                ReportPropertyChanging("ALU");
                _ALU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ALU");
                OnALUChanged();
            }
        }
        private global::System.String _ALU;
        partial void OnALUChanging(global::System.String value);
        partial void OnALUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemName
        {
            get
            {
                return _ItemName;
            }
            set
            {
                OnItemNameChanging(value);
                ReportPropertyChanging("ItemName");
                _ItemName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemName");
                OnItemNameChanged();
            }
        }
        private global::System.String _ItemName;
        partial void OnItemNameChanging(global::System.String value);
        partial void OnItemNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.String _Size;
        partial void OnSizeChanging(global::System.String value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentCode
        {
            get
            {
                return _DepartmentCode;
            }
            set
            {
                OnDepartmentCodeChanging(value);
                ReportPropertyChanging("DepartmentCode");
                _DepartmentCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentCode");
                OnDepartmentCodeChanged();
            }
        }
        private global::System.String _DepartmentCode;
        partial void OnDepartmentCodeChanging(global::System.String value);
        partial void OnDepartmentCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemNumber
        {
            get
            {
                return _ItemNumber;
            }
            set
            {
                OnItemNumberChanging(value);
                ReportPropertyChanging("ItemNumber");
                _ItemNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemNumber");
                OnItemNumberChanged();
            }
        }
        private global::System.Int32 _ItemNumber;
        partial void OnItemNumberChanging(global::System.Int32 value);
        partial void OnItemNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemType
        {
            get
            {
                return _ItemType;
            }
            set
            {
                OnItemTypeChanging(value);
                ReportPropertyChanging("ItemType");
                _ItemType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemType");
                OnItemTypeChanged();
            }
        }
        private global::System.String _ItemType;
        partial void OnItemTypeChanging(global::System.String value);
        partial void OnItemTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TaxCode
        {
            get
            {
                return _TaxCode;
            }
            set
            {
                OnTaxCodeChanging(value);
                ReportPropertyChanging("TaxCode");
                _TaxCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TaxCode");
                OnTaxCodeChanged();
            }
        }
        private global::System.String _TaxCode;
        partial void OnTaxCodeChanging(global::System.String value);
        partial void OnTaxCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Double> _Price;
        partial void OnPriceChanging(Nullable<global::System.Double> value);
        partial void OnPriceChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QBPOSModel", Name="SalesReceipt")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SalesReceipt : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SalesReceipt object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="salesReceiptNumber">Initial value of the SalesReceiptNumber property.</param>
        /// <param name="txnDate">Initial value of the TxnDate property.</param>
        /// <param name="associate">Initial value of the Associate property.</param>
        /// <param name="cashier">Initial value of the Cashier property.</param>
        /// <param name="comments">Initial value of the Comments property.</param>
        /// <param name="storeNumber">Initial value of the StoreNumber property.</param>
        /// <param name="workstation">Initial value of the Workstation property.</param>
        /// <param name="txnState">Initial value of the TxnState property.</param>
        /// <param name="salesReceiptType">Initial value of the SalesReceiptType property.</param>
        /// <param name="discount">Initial value of the Discount property.</param>
        public static SalesReceipt CreateSalesReceipt(global::System.Int32 id, global::System.String salesReceiptNumber, global::System.DateTime txnDate, global::System.String associate, global::System.String cashier, global::System.String comments, global::System.String storeNumber, global::System.String workstation, global::System.String txnState, global::System.String salesReceiptType, global::System.String discount)
        {
            SalesReceipt salesReceipt = new SalesReceipt();
            salesReceipt.Id = id;
            salesReceipt.SalesReceiptNumber = salesReceiptNumber;
            salesReceipt.TxnDate = txnDate;
            salesReceipt.Associate = associate;
            salesReceipt.Cashier = cashier;
            salesReceipt.Comments = comments;
            salesReceipt.StoreNumber = storeNumber;
            salesReceipt.Workstation = workstation;
            salesReceipt.TxnState = txnState;
            salesReceipt.SalesReceiptType = salesReceiptType;
            salesReceipt.Discount = discount;
            return salesReceipt;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SalesReceiptNumber
        {
            get
            {
                return _SalesReceiptNumber;
            }
            set
            {
                OnSalesReceiptNumberChanging(value);
                ReportPropertyChanging("SalesReceiptNumber");
                _SalesReceiptNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SalesReceiptNumber");
                OnSalesReceiptNumberChanged();
            }
        }
        private global::System.String _SalesReceiptNumber;
        partial void OnSalesReceiptNumberChanging(global::System.String value);
        partial void OnSalesReceiptNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TxnDate
        {
            get
            {
                return _TxnDate;
            }
            set
            {
                OnTxnDateChanging(value);
                ReportPropertyChanging("TxnDate");
                _TxnDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TxnDate");
                OnTxnDateChanged();
            }
        }
        private global::System.DateTime _TxnDate;
        partial void OnTxnDateChanging(global::System.DateTime value);
        partial void OnTxnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Associate
        {
            get
            {
                return _Associate;
            }
            set
            {
                OnAssociateChanging(value);
                ReportPropertyChanging("Associate");
                _Associate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Associate");
                OnAssociateChanged();
            }
        }
        private global::System.String _Associate;
        partial void OnAssociateChanging(global::System.String value);
        partial void OnAssociateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cashier
        {
            get
            {
                return _Cashier;
            }
            set
            {
                OnCashierChanging(value);
                ReportPropertyChanging("Cashier");
                _Cashier = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cashier");
                OnCashierChanged();
            }
        }
        private global::System.String _Cashier;
        partial void OnCashierChanging(global::System.String value);
        partial void OnCashierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StoreNumber
        {
            get
            {
                return _StoreNumber;
            }
            set
            {
                OnStoreNumberChanging(value);
                ReportPropertyChanging("StoreNumber");
                _StoreNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StoreNumber");
                OnStoreNumberChanged();
            }
        }
        private global::System.String _StoreNumber;
        partial void OnStoreNumberChanging(global::System.String value);
        partial void OnStoreNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Workstation
        {
            get
            {
                return _Workstation;
            }
            set
            {
                OnWorkstationChanging(value);
                ReportPropertyChanging("Workstation");
                _Workstation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Workstation");
                OnWorkstationChanged();
            }
        }
        private global::System.String _Workstation;
        partial void OnWorkstationChanging(global::System.String value);
        partial void OnWorkstationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TxnState
        {
            get
            {
                return _TxnState;
            }
            set
            {
                OnTxnStateChanging(value);
                ReportPropertyChanging("TxnState");
                _TxnState = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TxnState");
                OnTxnStateChanged();
            }
        }
        private global::System.String _TxnState;
        partial void OnTxnStateChanging(global::System.String value);
        partial void OnTxnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TxnID
        {
            get
            {
                return _TxnID;
            }
            set
            {
                OnTxnIDChanging(value);
                ReportPropertyChanging("TxnID");
                _TxnID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TxnID");
                OnTxnIDChanged();
            }
        }
        private global::System.String _TxnID;
        partial void OnTxnIDChanging(global::System.String value);
        partial void OnTxnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SalesReceiptType
        {
            get
            {
                return _SalesReceiptType;
            }
            set
            {
                OnSalesReceiptTypeChanging(value);
                ReportPropertyChanging("SalesReceiptType");
                _SalesReceiptType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SalesReceiptType");
                OnSalesReceiptTypeChanged();
            }
        }
        private global::System.String _SalesReceiptType;
        partial void OnSalesReceiptTypeChanging(global::System.String value);
        partial void OnSalesReceiptTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TrackingNumber
        {
            get
            {
                return _TrackingNumber;
            }
            set
            {
                OnTrackingNumberChanging(value);
                ReportPropertyChanging("TrackingNumber");
                _TrackingNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TrackingNumber");
                OnTrackingNumberChanged();
            }
        }
        private global::System.String _TrackingNumber;
        partial void OnTrackingNumberChanging(global::System.String value);
        partial void OnTrackingNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Discount
        {
            get
            {
                return _Discount;
            }
            set
            {
                OnDiscountChanging(value);
                ReportPropertyChanging("Discount");
                _Discount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Discount");
                OnDiscountChanged();
            }
        }
        private global::System.String _Discount;
        partial void OnDiscountChanging(global::System.String value);
        partial void OnDiscountChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QBPOSModel", "FK_SalesReceiptSalesReceiptDetails", "SalesReceiptDetail")]
        public EntityCollection<SalesReceiptDetail> SalesReceiptDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SalesReceiptDetail>("QBPOSModel.FK_SalesReceiptSalesReceiptDetails", "SalesReceiptDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SalesReceiptDetail>("QBPOSModel.FK_SalesReceiptSalesReceiptDetails", "SalesReceiptDetail", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QBPOSModel", Name="SalesReceiptDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SalesReceiptDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SalesReceiptDetail object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="salesReceiptId">Initial value of the SalesReceiptId property.</param>
        /// <param name="itemListID">Initial value of the ItemListID property.</param>
        /// <param name="qtySold">Initial value of the QtySold property.</param>
        /// <param name="itemKey">Initial value of the ItemKey property.</param>
        /// <param name="tax">Initial value of the Tax property.</param>
        public static SalesReceiptDetail CreateSalesReceiptDetail(global::System.Int32 id, global::System.Int32 salesReceiptId, global::System.String itemListID, global::System.Decimal qtySold, global::System.String itemKey, global::System.Decimal tax)
        {
            SalesReceiptDetail salesReceiptDetail = new SalesReceiptDetail();
            salesReceiptDetail.Id = id;
            salesReceiptDetail.SalesReceiptId = salesReceiptId;
            salesReceiptDetail.ItemListID = itemListID;
            salesReceiptDetail.QtySold = qtySold;
            salesReceiptDetail.ItemKey = itemKey;
            salesReceiptDetail.Tax = tax;
            return salesReceiptDetail;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SalesReceiptId
        {
            get
            {
                return _SalesReceiptId;
            }
            set
            {
                OnSalesReceiptIdChanging(value);
                ReportPropertyChanging("SalesReceiptId");
                _SalesReceiptId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SalesReceiptId");
                OnSalesReceiptIdChanged();
            }
        }
        private global::System.Int32 _SalesReceiptId;
        partial void OnSalesReceiptIdChanging(global::System.Int32 value);
        partial void OnSalesReceiptIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemListID
        {
            get
            {
                return _ItemListID;
            }
            set
            {
                OnItemListIDChanging(value);
                ReportPropertyChanging("ItemListID");
                _ItemListID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemListID");
                OnItemListIDChanged();
            }
        }
        private global::System.String _ItemListID;
        partial void OnItemListIDChanging(global::System.String value);
        partial void OnItemListIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal QtySold
        {
            get
            {
                return _QtySold;
            }
            set
            {
                OnQtySoldChanging(value);
                ReportPropertyChanging("QtySold");
                _QtySold = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QtySold");
                OnQtySoldChanged();
            }
        }
        private global::System.Decimal _QtySold;
        partial void OnQtySoldChanging(global::System.Decimal value);
        partial void OnQtySoldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemKey
        {
            get
            {
                return _ItemKey;
            }
            set
            {
                OnItemKeyChanging(value);
                ReportPropertyChanging("ItemKey");
                _ItemKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemKey");
                OnItemKeyChanged();
            }
        }
        private global::System.String _ItemKey;
        partial void OnItemKeyChanging(global::System.String value);
        partial void OnItemKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Tax
        {
            get
            {
                return _Tax;
            }
            set
            {
                OnTaxChanging(value);
                ReportPropertyChanging("Tax");
                _Tax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tax");
                OnTaxChanged();
            }
        }
        private global::System.Decimal _Tax;
        partial void OnTaxChanging(global::System.Decimal value);
        partial void OnTaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> QtyAllocated
        {
            get
            {
                return _QtyAllocated;
            }
            set
            {
                OnQtyAllocatedChanging(value);
                ReportPropertyChanging("QtyAllocated");
                _QtyAllocated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QtyAllocated");
                OnQtyAllocatedChanged();
            }
        }
        private Nullable<global::System.Decimal> _QtyAllocated;
        partial void OnQtyAllocatedChanging(Nullable<global::System.Decimal> value);
        partial void OnQtyAllocatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemDesc1
        {
            get
            {
                return _ItemDesc1;
            }
            set
            {
                OnItemDesc1Changing(value);
                ReportPropertyChanging("ItemDesc1");
                _ItemDesc1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemDesc1");
                OnItemDesc1Changed();
            }
        }
        private global::System.String _ItemDesc1;
        partial void OnItemDesc1Changing(global::System.String value);
        partial void OnItemDesc1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemDesc2
        {
            get
            {
                return _ItemDesc2;
            }
            set
            {
                OnItemDesc2Changing(value);
                ReportPropertyChanging("ItemDesc2");
                _ItemDesc2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemDesc2");
                OnItemDesc2Changed();
            }
        }
        private global::System.String _ItemDesc2;
        partial void OnItemDesc2Changing(global::System.String value);
        partial void OnItemDesc2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemALU
        {
            get
            {
                return _ItemALU;
            }
            set
            {
                OnItemALUChanging(value);
                ReportPropertyChanging("ItemALU");
                _ItemALU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemALU");
                OnItemALUChanged();
            }
        }
        private global::System.String _ItemALU;
        partial void OnItemALUChanging(global::System.String value);
        partial void OnItemALUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Double> _Price;
        partial void OnPriceChanging(Nullable<global::System.Double> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TaxCode
        {
            get
            {
                return _TaxCode;
            }
            set
            {
                OnTaxCodeChanging(value);
                ReportPropertyChanging("TaxCode");
                _TaxCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TaxCode");
                OnTaxCodeChanged();
            }
        }
        private global::System.String _TaxCode;
        partial void OnTaxCodeChanging(global::System.String value);
        partial void OnTaxCodeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QBPOSModel", "FK_SalesReceiptSalesReceiptDetails", "SalesReceipt")]
        public SalesReceipt SalesReceipt
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SalesReceipt>("QBPOSModel.FK_SalesReceiptSalesReceiptDetails", "SalesReceipt").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SalesReceipt>("QBPOSModel.FK_SalesReceiptSalesReceiptDetails", "SalesReceipt").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SalesReceipt> SalesReceiptReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SalesReceipt>("QBPOSModel.FK_SalesReceiptSalesReceiptDetails", "SalesReceipt");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SalesReceipt>("QBPOSModel.FK_SalesReceiptSalesReceiptDetails", "SalesReceipt", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
