//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Batch()
        {
            this.TransactionBase = new HashSet<TransactionBase>();
            this.CloseTransactionBase = new HashSet<TransactionBase>();
        }
    
        public int BatchId { get; set; }
        public double OpeningCash { get; set; }
        public Nullable<double> EndingCash { get; set; }
        public System.DateTime OpeningTime { get; set; }
        public Nullable<System.DateTime> ClosingTime { get; set; }
        public Nullable<double> TotalTender { get; set; }
        public Nullable<double> TotalChange { get; set; }
        public string Status { get; set; }
        public int StationId { get; set; }
        public int OpeningCashier { get; set; }
        public Nullable<int> ClosingCashier { get; set; }
        public double Sales { get; set; }
        public int OpenTransactions { get; set; }
        public int CloseTransactions { get; set; }
        public byte[] EntryTimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionBase> TransactionBase { get; set; }
        public virtual Station Station { get; set; }
        public virtual Cashier OpenCashier { get; set; }
        public virtual Cashier CloseCashier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionBase> CloseTransactionBase { get; set; }
    }
}
