//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashierLog
    {
        public int CashierLogId { get; set; }
        public string MachineName { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public string Status { get; set; }
        public int PersonId { get; set; }
        public byte[] EntryTimeStamp { get; set; }
    
        public virtual Cashier Cashier { get; set; }
    }
}
