//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System.ComponentModel;
    using TrackableEntities;
    using System;
    using System.Collections.Generic;
    using TrackableEntities.Client;
    
    public partial class Company : EntityBase
    {
        public Company()
        {
            this.Store = new ChangeTrackingCollection<Store>();
            CustomStartup();
            this.PropertyChanged += UpdatePropertyChanged;
        }
        partial void CustomStartup();
    
            private void UpdatePropertyChanged(object sender, PropertyChangedEventArgs e)
            {
                if (!string.IsNullOrEmpty(e.PropertyName) && (!Environment.StackTrace.Contains("Internal.Materialization")) && TrackingState == TrackingState.Unchanged)
                {
                    TrackingState = TrackingState.Modified;
                }
            }
        
    	public int CompanyId
    	{ 
    		get { return _CompanyId; }
    		set
    		{
    			if (Equals(value, _CompanyId)) return;
    			_CompanyId = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private int _CompanyId;
        
    	public string CompanyName
    	{ 
    		get { return _CompanyName; }
    		set
    		{
    			if (Equals(value, _CompanyName)) return;
    			_CompanyName = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _CompanyName;
        
    	public string Address
    	{ 
    		get { return _Address; }
    		set
    		{
    			if (Equals(value, _Address)) return;
    			_Address = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Address;
        
    	public string Address1
    	{ 
    		get { return _Address1; }
    		set
    		{
    			if (Equals(value, _Address1)) return;
    			_Address1 = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Address1;
        
    	public string SoftwareName
    	{ 
    		get { return _SoftwareName; }
    		set
    		{
    			if (Equals(value, _SoftwareName)) return;
    			_SoftwareName = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _SoftwareName;
        
    	public string PhoneNumber
    	{ 
    		get { return _PhoneNumber; }
    		set
    		{
    			if (Equals(value, _PhoneNumber)) return;
    			_PhoneNumber = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _PhoneNumber;
        
    	public string Motto
    	{ 
    		get { return _Motto; }
    		set
    		{
    			if (Equals(value, _Motto)) return;
    			_Motto = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Motto;
        
    	public byte[] EntryTimeStamp
    	{ 
    		get { return _EntryTimeStamp; }
    		set
    		{
    			if (Equals(value, _EntryTimeStamp)) return;
    			_EntryTimeStamp = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private byte[] _EntryTimeStamp;
    
    	public ChangeTrackingCollection<Store> Store
    	{
    		get { return _Store; }
    		set
    		{
    			if (Equals(value, _Store)) return;
    			_Store = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private ChangeTrackingCollection<Store> _Store;
    }
}
