//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.SalesTax = 0m;
            this.TransactionEntryBase = new HashSet<TransactionEntryBase>();
            this.ItemDosages = new HashSet<ItemDosage>();
        }
    
        public string Description { get; set; }
        public Nullable<bool> ItemNotDiscountable { get; set; }
        public int ItemId { get; set; }
        public string ItemLookupCode { get; set; }
        public string Department { get; set; }
        public string Category { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public double Quantity { get; set; }
        public string ExtendedDescription { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public string QBItemListID { get; set; }
        public string UnitOfMeasure { get; set; }
        public string ItemName { get; set; }
        public string ItemNumber { get; set; }
        public string Size { get; set; }
        public byte[] EntryTimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionEntryBase> TransactionEntryBase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemDosage> ItemDosages { get; set; }
    }
}
