//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionEntry : TransactionEntryBase
    {
        public string Dosage { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Repeat { get; set; }
        public Nullable<int> RepeatCount { get; set; }
    }
}
