//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBInventoryItem
    {
        public string ListID { get; set; }
        public string ItemDesc2 { get; set; }
        public string ItemName { get; set; }
        public string Size { get; set; }
        public string DepartmentCode { get; set; }
        public int ItemNumber { get; set; }
        public string TaxCode { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public byte[] EntryTimeStamp { get; set; }
    }
}
