//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchView
    {
        public System.DateTime Time { get; set; }
        public int TransactionId { get; set; }
        public int ItemId { get; set; }
        public string ItemInfo { get; set; }
        public int PatientId { get; set; }
        public string PatientInfo { get; set; }
        public int DoctorId { get; set; }
        public string DoctorInfo { get; set; }
        public string SearchInfo { get; set; }
    
        public virtual Prescription Prescription { get; set; }
    }
}
