//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.TransactionSeed = 0;
            this.SeedTransaction = 0;
            this.Station = new HashSet<Station>();
        }
    
        public int StoreId { get; set; }
        public string StoreCode { get; set; }
        public string StoreAddress { get; set; }
        public int CompanyId { get; set; }
        public int TransactionSeed { get; set; }
        public int SeedTransaction { get; set; }
        public byte[] EntryTimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station> Station { get; set; }
        public virtual Company Company { get; set; }
    }
}
