//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionEntryBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionEntryBase()
        {
            this.Quantity = 1m;
            this.Taxable = true;
            this.Discount = 0m;
        }
    
        public int StoreID { get; set; }
        public int TransactionEntryId { get; set; }
        public int TransactionId { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public bool Taxable { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
        public decimal SalesTaxPercent { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<short> EntryNumber { get; set; }
        public byte[] EntryTimeStamp { get; set; }
        public int ItemId { get; set; }
    
        public virtual TransactionBase Transaction { get; set; }
        public virtual Item Item { get; set; }
    }
}
