//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionBase()
        {
            this.TransactionEntries = new HashSet<TransactionEntryBase>();
        }
    
        public int StationId { get; set; }
        public int BatchId { get; set; }
        public Nullable<int> CloseBatchId { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int CashierId { get; set; }
        public string Comment { get; set; }
        public string ReferenceNumber { get; set; }
        public string StoreCode { get; set; }
        public int TransactionId { get; set; }
        public bool OpenClose { get; set; }
        public Nullable<int> PharmacistId { get; set; }
        public string Status { get; set; }
        public byte[] EntryTimeStamp { get; set; }
        public string TransactionNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionEntryBase> TransactionEntries { get; set; }
        public virtual Person Customer { get; set; }
        public virtual Cashier Cashier { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual Station Station { get; set; }
        public virtual Batch CloseBatch { get; set; }
        public virtual Cashier Pharmacist { get; set; }
    }
}
