// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>QuickBooks</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace QuickBooks
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class ItemInventoryRet
    {

        private string listIDField;

        private string timeCreatedField;

        private string timeModifiedField;

        private string editSequenceField;

        private string nameField;

        private string fullNameField;

        private string barCodeValueField;

        private bool isActiveField;

        private ItemInventoryRetClassRef classRefField;

        private ItemInventoryRetParentRef parentRefField;

        private ushort sublevelField;

        private string manufacturerPartNumberField;

        private ItemInventoryRetUnitOfMeasureSetRef unitOfMeasureSetRefField;

        private ItemInventoryRetSalesTaxCodeRef salesTaxCodeRefField;

        private string salesDescField;

        private decimal salesPriceField;

        private ItemInventoryRetIncomeAccountRef incomeAccountRefField;

        private string purchaseDescField;

        private decimal purchaseCostField;

        private ItemInventoryRetCOGSAccountRef cOGSAccountRefField;

        private ItemInventoryRetPrefVendorRef prefVendorRefField;

        private ItemInventoryRetAssetAccountRef assetAccountRefField;

        private decimal reorderPointField;

        private decimal maxField;

        private decimal quantityOnHandField;

        private decimal averageCostField;

        private decimal quantityOnOrderField;

        private decimal quantityOnSalesOrderField;

        private string externalGUIDField;

        private ItemInventoryRetDataExtRet dataExtRetField;

        public ItemInventoryRet()
        {
            this.dataExtRetField = new ItemInventoryRetDataExtRet();
            this.assetAccountRefField = new ItemInventoryRetAssetAccountRef();
            this.prefVendorRefField = new ItemInventoryRetPrefVendorRef();
            this.cOGSAccountRefField = new ItemInventoryRetCOGSAccountRef();
            this.incomeAccountRefField = new ItemInventoryRetIncomeAccountRef();
            this.salesTaxCodeRefField = new ItemInventoryRetSalesTaxCodeRef();
            this.unitOfMeasureSetRefField = new ItemInventoryRetUnitOfMeasureSetRef();
            this.parentRefField = new ItemInventoryRetParentRef();
            this.classRefField = new ItemInventoryRetClassRef();
        }

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string TimeCreated
        {
            get
            {
                return this.timeCreatedField;
            }
            set
            {
                this.timeCreatedField = value;
            }
        }

        public string TimeModified
        {
            get
            {
                return this.timeModifiedField;
            }
            set
            {
                this.timeModifiedField = value;
            }
        }

        public string EditSequence
        {
            get
            {
                return this.editSequenceField;
            }
            set
            {
                this.editSequenceField = value;
            }
        }

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }

        public string BarCodeValue
        {
            get
            {
                return this.barCodeValueField;
            }
            set
            {
                this.barCodeValueField = value;
            }
        }

        public bool IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }

        public ItemInventoryRetClassRef ClassRef
        {
            get
            {
                return this.classRefField;
            }
            set
            {
                this.classRefField = value;
            }
        }

        public ItemInventoryRetParentRef ParentRef
        {
            get
            {
                return this.parentRefField;
            }
            set
            {
                this.parentRefField = value;
            }
        }

        public ushort Sublevel
        {
            get
            {
                return this.sublevelField;
            }
            set
            {
                this.sublevelField = value;
            }
        }

        public string ManufacturerPartNumber
        {
            get
            {
                return this.manufacturerPartNumberField;
            }
            set
            {
                this.manufacturerPartNumberField = value;
            }
        }

        public ItemInventoryRetUnitOfMeasureSetRef UnitOfMeasureSetRef
        {
            get
            {
                return this.unitOfMeasureSetRefField;
            }
            set
            {
                this.unitOfMeasureSetRefField = value;
            }
        }

        public ItemInventoryRetSalesTaxCodeRef SalesTaxCodeRef
        {
            get
            {
                return this.salesTaxCodeRefField;
            }
            set
            {
                this.salesTaxCodeRefField = value;
            }
        }

        public string SalesDesc
        {
            get
            {
                return this.salesDescField;
            }
            set
            {
                this.salesDescField = value;
            }
        }

        public decimal SalesPrice
        {
            get
            {
                return this.salesPriceField;
            }
            set
            {
                this.salesPriceField = value;
            }
        }

        public ItemInventoryRetIncomeAccountRef IncomeAccountRef
        {
            get
            {
                return this.incomeAccountRefField;
            }
            set
            {
                this.incomeAccountRefField = value;
            }
        }

        public string PurchaseDesc
        {
            get
            {
                return this.purchaseDescField;
            }
            set
            {
                this.purchaseDescField = value;
            }
        }

        public decimal PurchaseCost
        {
            get
            {
                return this.purchaseCostField;
            }
            set
            {
                this.purchaseCostField = value;
            }
        }

        public ItemInventoryRetCOGSAccountRef COGSAccountRef
        {
            get
            {
                return this.cOGSAccountRefField;
            }
            set
            {
                this.cOGSAccountRefField = value;
            }
        }

        public ItemInventoryRetPrefVendorRef PrefVendorRef
        {
            get
            {
                return this.prefVendorRefField;
            }
            set
            {
                this.prefVendorRefField = value;
            }
        }

        public ItemInventoryRetAssetAccountRef AssetAccountRef
        {
            get
            {
                return this.assetAccountRefField;
            }
            set
            {
                this.assetAccountRefField = value;
            }
        }

        public decimal ReorderPoint
        {
            get
            {
                return this.reorderPointField;
            }
            set
            {
                this.reorderPointField = value;
            }
        }

        public decimal Max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }

        public decimal QuantityOnHand
        {
            get
            {
                return this.quantityOnHandField;
            }
            set
            {
                this.quantityOnHandField = value;
            }
        }

        public decimal AverageCost
        {
            get
            {
                return this.averageCostField;
            }
            set
            {
                this.averageCostField = value;
            }
        }

        public decimal QuantityOnOrder
        {
            get
            {
                return this.quantityOnOrderField;
            }
            set
            {
                this.quantityOnOrderField = value;
            }
        }

        public decimal QuantityOnSalesOrder
        {
            get
            {
                return this.quantityOnSalesOrderField;
            }
            set
            {
                this.quantityOnSalesOrderField = value;
            }
        }

        public string ExternalGUID
        {
            get
            {
                return this.externalGUIDField;
            }
            set
            {
                this.externalGUIDField = value;
            }
        }

        public ItemInventoryRetDataExtRet DataExtRet
        {
            get
            {
                return this.dataExtRetField;
            }
            set
            {
                this.dataExtRetField = value;
            }
        }
    }

    public partial class ItemInventoryRetClassRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class ItemInventoryRetParentRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class ItemInventoryRetUnitOfMeasureSetRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class ItemInventoryRetSalesTaxCodeRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class ItemInventoryRetIncomeAccountRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class ItemInventoryRetCOGSAccountRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class ItemInventoryRetPrefVendorRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class ItemInventoryRetAssetAccountRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class ItemInventoryRetDataExtRet
    {

        private string ownerIDField;

        private string dataExtNameField;

        private string dataExtTypeField;

        private string dataExtValueField;

        public string OwnerID
        {
            get
            {
                return this.ownerIDField;
            }
            set
            {
                this.ownerIDField = value;
            }
        }

        public string DataExtName
        {
            get
            {
                return this.dataExtNameField;
            }
            set
            {
                this.dataExtNameField = value;
            }
        }

        public string DataExtType
        {
            get
            {
                return this.dataExtTypeField;
            }
            set
            {
                this.dataExtTypeField = value;
            }
        }

        public string DataExtValue
        {
            get
            {
                return this.dataExtValueField;
            }
            set
            {
                this.dataExtValueField = value;
            }
        }
    }
}
