// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>QuickBooks</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace QuickBooks
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class SalesReceiptRet
    {

        private string txnIDField;

        private string timeCreatedField;

        private string timeModifiedField;

        private string editSequenceField;

        private int txnNumberField;

        private SalesReceiptRetCustomerRef customerRefField;

        private SalesReceiptRetClassRef classRefField;

        private SalesReceiptRetTemplateRef templateRefField;

        private string txnDateField;

        private string refNumberField;

        private SalesReceiptRetBillAddress billAddressField;

        private SalesReceiptRetBillAddressBlock billAddressBlockField;

        private SalesReceiptRetShipAddress shipAddressField;

        private SalesReceiptRetShipAddressBlock shipAddressBlockField;

        private bool isPendingField;

        private string checkNumberField;

        private SalesReceiptRetPaymentMethodRef paymentMethodRefField;

        private string dueDateField;

        private SalesReceiptRetSalesRepRef salesRepRefField;

        private string shipDateField;

        private SalesReceiptRetShipMethodRef shipMethodRefField;

        private string fOBField;

        private decimal subtotalField;

        private SalesReceiptRetItemSalesTaxRef itemSalesTaxRefField;

        private string salesTaxPercentageField;

        private decimal salesTaxTotalField;

        private decimal totalAmountField;

        private SalesReceiptRetCurrencyRef currencyRefField;

        private decimal exchangeRateField;

        private decimal totalAmountInHomeCurrencyField;

        private string memoField;

        private SalesReceiptRetCustomerMsgRef customerMsgRefField;

        private bool isToBePrintedField;

        private bool isToBeEmailedField;

        private SalesReceiptRetCustomerSalesTaxCodeRef customerSalesTaxCodeRefField;

        private SalesReceiptRetDepositToAccountRef depositToAccountRefField;

        private SalesReceiptRetCreditCardTxnInfo creditCardTxnInfoField;

        private string otherField;

        private string externalGUIDField;

        private List<SalesReceiptRetSalesReceiptLineRet> salesReceiptLineRetField;

        private SalesReceiptRetSalesReceiptLineGroupRet salesReceiptLineGroupRetField;

        private SalesReceiptRetDataExtRet dataExtRetField;

        public SalesReceiptRet()
        {
            this.dataExtRetField = new SalesReceiptRetDataExtRet();
            this.salesReceiptLineGroupRetField = new SalesReceiptRetSalesReceiptLineGroupRet();
            this.salesReceiptLineRetField = new List<SalesReceiptRetSalesReceiptLineRet>();
            this.creditCardTxnInfoField = new SalesReceiptRetCreditCardTxnInfo();
            this.depositToAccountRefField = new SalesReceiptRetDepositToAccountRef();
            this.customerSalesTaxCodeRefField = new SalesReceiptRetCustomerSalesTaxCodeRef();
            this.customerMsgRefField = new SalesReceiptRetCustomerMsgRef();
            this.currencyRefField = new SalesReceiptRetCurrencyRef();
            this.itemSalesTaxRefField = new SalesReceiptRetItemSalesTaxRef();
            this.shipMethodRefField = new SalesReceiptRetShipMethodRef();
            this.salesRepRefField = new SalesReceiptRetSalesRepRef();
            this.paymentMethodRefField = new SalesReceiptRetPaymentMethodRef();
            this.shipAddressBlockField = new SalesReceiptRetShipAddressBlock();
            this.shipAddressField = new SalesReceiptRetShipAddress();
            this.billAddressBlockField = new SalesReceiptRetBillAddressBlock();
            this.billAddressField = new SalesReceiptRetBillAddress();
            this.templateRefField = new SalesReceiptRetTemplateRef();
            this.classRefField = new SalesReceiptRetClassRef();
            this.customerRefField = new SalesReceiptRetCustomerRef();
        }

        public string TxnID
        {
            get
            {
                return this.txnIDField;
            }
            set
            {
                this.txnIDField = value;
            }
        }

        public string TimeCreated
        {
            get
            {
                return this.timeCreatedField;
            }
            set
            {
                this.timeCreatedField = value;
            }
        }

        public string TimeModified
        {
            get
            {
                return this.timeModifiedField;
            }
            set
            {
                this.timeModifiedField = value;
            }
        }

        public string EditSequence
        {
            get
            {
                return this.editSequenceField;
            }
            set
            {
                this.editSequenceField = value;
            }
        }

        public int TxnNumber
        {
            get
            {
                return this.txnNumberField;
            }
            set
            {
                this.txnNumberField = value;
            }
        }

        public SalesReceiptRetCustomerRef CustomerRef
        {
            get
            {
                return this.customerRefField;
            }
            set
            {
                this.customerRefField = value;
            }
        }

        public SalesReceiptRetClassRef ClassRef
        {
            get
            {
                return this.classRefField;
            }
            set
            {
                this.classRefField = value;
            }
        }

        public SalesReceiptRetTemplateRef TemplateRef
        {
            get
            {
                return this.templateRefField;
            }
            set
            {
                this.templateRefField = value;
            }
        }

        public string TxnDate
        {
            get
            {
                return this.txnDateField;
            }
            set
            {
                this.txnDateField = value;
            }
        }

        public string RefNumber
        {
            get
            {
                return this.refNumberField;
            }
            set
            {
                this.refNumberField = value;
            }
        }

        public SalesReceiptRetBillAddress BillAddress
        {
            get
            {
                return this.billAddressField;
            }
            set
            {
                this.billAddressField = value;
            }
        }

        public SalesReceiptRetBillAddressBlock BillAddressBlock
        {
            get
            {
                return this.billAddressBlockField;
            }
            set
            {
                this.billAddressBlockField = value;
            }
        }

        public SalesReceiptRetShipAddress ShipAddress
        {
            get
            {
                return this.shipAddressField;
            }
            set
            {
                this.shipAddressField = value;
            }
        }

        public SalesReceiptRetShipAddressBlock ShipAddressBlock
        {
            get
            {
                return this.shipAddressBlockField;
            }
            set
            {
                this.shipAddressBlockField = value;
            }
        }

        public bool IsPending
        {
            get
            {
                return this.isPendingField;
            }
            set
            {
                this.isPendingField = value;
            }
        }

        public string CheckNumber
        {
            get
            {
                return this.checkNumberField;
            }
            set
            {
                this.checkNumberField = value;
            }
        }

        public SalesReceiptRetPaymentMethodRef PaymentMethodRef
        {
            get
            {
                return this.paymentMethodRefField;
            }
            set
            {
                this.paymentMethodRefField = value;
            }
        }

        public string DueDate
        {
            get
            {
                return this.dueDateField;
            }
            set
            {
                this.dueDateField = value;
            }
        }

        public SalesReceiptRetSalesRepRef SalesRepRef
        {
            get
            {
                return this.salesRepRefField;
            }
            set
            {
                this.salesRepRefField = value;
            }
        }

        public string ShipDate
        {
            get
            {
                return this.shipDateField;
            }
            set
            {
                this.shipDateField = value;
            }
        }

        public SalesReceiptRetShipMethodRef ShipMethodRef
        {
            get
            {
                return this.shipMethodRefField;
            }
            set
            {
                this.shipMethodRefField = value;
            }
        }

        public string FOB
        {
            get
            {
                return this.fOBField;
            }
            set
            {
                this.fOBField = value;
            }
        }

        public decimal Subtotal
        {
            get
            {
                return this.subtotalField;
            }
            set
            {
                this.subtotalField = value;
            }
        }

        public SalesReceiptRetItemSalesTaxRef ItemSalesTaxRef
        {
            get
            {
                return this.itemSalesTaxRefField;
            }
            set
            {
                this.itemSalesTaxRefField = value;
            }
        }

        public string SalesTaxPercentage
        {
            get
            {
                return this.salesTaxPercentageField;
            }
            set
            {
                this.salesTaxPercentageField = value;
            }
        }

        public decimal SalesTaxTotal
        {
            get
            {
                return this.salesTaxTotalField;
            }
            set
            {
                this.salesTaxTotalField = value;
            }
        }

        public decimal TotalAmount
        {
            get
            {
                return this.totalAmountField;
            }
            set
            {
                this.totalAmountField = value;
            }
        }

        public SalesReceiptRetCurrencyRef CurrencyRef
        {
            get
            {
                return this.currencyRefField;
            }
            set
            {
                this.currencyRefField = value;
            }
        }

        public decimal ExchangeRate
        {
            get
            {
                return this.exchangeRateField;
            }
            set
            {
                this.exchangeRateField = value;
            }
        }

        public decimal TotalAmountInHomeCurrency
        {
            get
            {
                return this.totalAmountInHomeCurrencyField;
            }
            set
            {
                this.totalAmountInHomeCurrencyField = value;
            }
        }

        public string Memo
        {
            get
            {
                return this.memoField;
            }
            set
            {
                this.memoField = value;
            }
        }

        public SalesReceiptRetCustomerMsgRef CustomerMsgRef
        {
            get
            {
                return this.customerMsgRefField;
            }
            set
            {
                this.customerMsgRefField = value;
            }
        }

        public bool IsToBePrinted
        {
            get
            {
                return this.isToBePrintedField;
            }
            set
            {
                this.isToBePrintedField = value;
            }
        }

        public bool IsToBeEmailed
        {
            get
            {
                return this.isToBeEmailedField;
            }
            set
            {
                this.isToBeEmailedField = value;
            }
        }

        public SalesReceiptRetCustomerSalesTaxCodeRef CustomerSalesTaxCodeRef
        {
            get
            {
                return this.customerSalesTaxCodeRefField;
            }
            set
            {
                this.customerSalesTaxCodeRefField = value;
            }
        }

        public SalesReceiptRetDepositToAccountRef DepositToAccountRef
        {
            get
            {
                return this.depositToAccountRefField;
            }
            set
            {
                this.depositToAccountRefField = value;
            }
        }

        public SalesReceiptRetCreditCardTxnInfo CreditCardTxnInfo
        {
            get
            {
                return this.creditCardTxnInfoField;
            }
            set
            {
                this.creditCardTxnInfoField = value;
            }
        }

        public string Other
        {
            get
            {
                return this.otherField;
            }
            set
            {
                this.otherField = value;
            }
        }

        public string ExternalGUID
        {
            get
            {
                return this.externalGUIDField;
            }
            set
            {
                this.externalGUIDField = value;
            }
        }

        public List<SalesReceiptRetSalesReceiptLineRet> SalesReceiptLineRet
        {
            get
            {
                return this.salesReceiptLineRetField;
            }
            set
            {
                this.salesReceiptLineRetField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRet SalesReceiptLineGroupRet
        {
            get
            {
                return this.salesReceiptLineGroupRetField;
            }
            set
            {
                this.salesReceiptLineGroupRetField = value;
            }
        }

        public SalesReceiptRetDataExtRet DataExtRet
        {
            get
            {
                return this.dataExtRetField;
            }
            set
            {
                this.dataExtRetField = value;
            }
        }
    }

    public partial class SalesReceiptRetCustomerRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetClassRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetTemplateRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetBillAddress
    {

        private string addr1Field;

        private string addr2Field;

        private string addr3Field;

        private string addr4Field;

        private string addr5Field;

        private string cityField;

        private string stateField;

        private string postalCodeField;

        private string countryField;

        private string noteField;

        public string Addr1
        {
            get
            {
                return this.addr1Field;
            }
            set
            {
                this.addr1Field = value;
            }
        }

        public string Addr2
        {
            get
            {
                return this.addr2Field;
            }
            set
            {
                this.addr2Field = value;
            }
        }

        public string Addr3
        {
            get
            {
                return this.addr3Field;
            }
            set
            {
                this.addr3Field = value;
            }
        }

        public string Addr4
        {
            get
            {
                return this.addr4Field;
            }
            set
            {
                this.addr4Field = value;
            }
        }

        public string Addr5
        {
            get
            {
                return this.addr5Field;
            }
            set
            {
                this.addr5Field = value;
            }
        }

        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
    }

    public partial class SalesReceiptRetBillAddressBlock
    {

        private string addr1Field;

        private string addr2Field;

        private string addr3Field;

        private string addr4Field;

        private string addr5Field;

        public string Addr1
        {
            get
            {
                return this.addr1Field;
            }
            set
            {
                this.addr1Field = value;
            }
        }

        public string Addr2
        {
            get
            {
                return this.addr2Field;
            }
            set
            {
                this.addr2Field = value;
            }
        }

        public string Addr3
        {
            get
            {
                return this.addr3Field;
            }
            set
            {
                this.addr3Field = value;
            }
        }

        public string Addr4
        {
            get
            {
                return this.addr4Field;
            }
            set
            {
                this.addr4Field = value;
            }
        }

        public string Addr5
        {
            get
            {
                return this.addr5Field;
            }
            set
            {
                this.addr5Field = value;
            }
        }
    }

    public partial class SalesReceiptRetShipAddress
    {

        private string addr1Field;

        private string addr2Field;

        private string addr3Field;

        private string addr4Field;

        private string addr5Field;

        private string cityField;

        private string stateField;

        private string postalCodeField;

        private string countryField;

        private string noteField;

        public string Addr1
        {
            get
            {
                return this.addr1Field;
            }
            set
            {
                this.addr1Field = value;
            }
        }

        public string Addr2
        {
            get
            {
                return this.addr2Field;
            }
            set
            {
                this.addr2Field = value;
            }
        }

        public string Addr3
        {
            get
            {
                return this.addr3Field;
            }
            set
            {
                this.addr3Field = value;
            }
        }

        public string Addr4
        {
            get
            {
                return this.addr4Field;
            }
            set
            {
                this.addr4Field = value;
            }
        }

        public string Addr5
        {
            get
            {
                return this.addr5Field;
            }
            set
            {
                this.addr5Field = value;
            }
        }

        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
    }

    public partial class SalesReceiptRetShipAddressBlock
    {

        private string addr1Field;

        private string addr2Field;

        private string addr3Field;

        private string addr4Field;

        private string addr5Field;

        public string Addr1
        {
            get
            {
                return this.addr1Field;
            }
            set
            {
                this.addr1Field = value;
            }
        }

        public string Addr2
        {
            get
            {
                return this.addr2Field;
            }
            set
            {
                this.addr2Field = value;
            }
        }

        public string Addr3
        {
            get
            {
                return this.addr3Field;
            }
            set
            {
                this.addr3Field = value;
            }
        }

        public string Addr4
        {
            get
            {
                return this.addr4Field;
            }
            set
            {
                this.addr4Field = value;
            }
        }

        public string Addr5
        {
            get
            {
                return this.addr5Field;
            }
            set
            {
                this.addr5Field = value;
            }
        }
    }

    public partial class SalesReceiptRetPaymentMethodRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesRepRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetShipMethodRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetItemSalesTaxRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetCurrencyRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetCustomerMsgRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetCustomerSalesTaxCodeRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetDepositToAccountRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetCreditCardTxnInfo
    {

        private SalesReceiptRetCreditCardTxnInfoCreditCardTxnInputInfo creditCardTxnInputInfoField;

        private SalesReceiptRetCreditCardTxnInfoCreditCardTxnResultInfo creditCardTxnResultInfoField;

        public SalesReceiptRetCreditCardTxnInfo()
        {
            this.creditCardTxnResultInfoField = new SalesReceiptRetCreditCardTxnInfoCreditCardTxnResultInfo();
            this.creditCardTxnInputInfoField = new SalesReceiptRetCreditCardTxnInfoCreditCardTxnInputInfo();
        }

        public SalesReceiptRetCreditCardTxnInfoCreditCardTxnInputInfo CreditCardTxnInputInfo
        {
            get
            {
                return this.creditCardTxnInputInfoField;
            }
            set
            {
                this.creditCardTxnInputInfoField = value;
            }
        }

        public SalesReceiptRetCreditCardTxnInfoCreditCardTxnResultInfo CreditCardTxnResultInfo
        {
            get
            {
                return this.creditCardTxnResultInfoField;
            }
            set
            {
                this.creditCardTxnResultInfoField = value;
            }
        }
    }

    public partial class SalesReceiptRetCreditCardTxnInfoCreditCardTxnInputInfo
    {

        private string creditCardNumberField;

        private int expirationMonthField;

        private int expirationYearField;

        private string nameOnCardField;

        private string creditCardAddressField;

        private string creditCardPostalCodeField;

        private string commercialCardCodeField;

        private string transactionModeField;

        private string creditCardTxnTypeField;

        public string CreditCardNumber
        {
            get
            {
                return this.creditCardNumberField;
            }
            set
            {
                this.creditCardNumberField = value;
            }
        }

        public int ExpirationMonth
        {
            get
            {
                return this.expirationMonthField;
            }
            set
            {
                this.expirationMonthField = value;
            }
        }

        public int ExpirationYear
        {
            get
            {
                return this.expirationYearField;
            }
            set
            {
                this.expirationYearField = value;
            }
        }

        public string NameOnCard
        {
            get
            {
                return this.nameOnCardField;
            }
            set
            {
                this.nameOnCardField = value;
            }
        }

        public string CreditCardAddress
        {
            get
            {
                return this.creditCardAddressField;
            }
            set
            {
                this.creditCardAddressField = value;
            }
        }

        public string CreditCardPostalCode
        {
            get
            {
                return this.creditCardPostalCodeField;
            }
            set
            {
                this.creditCardPostalCodeField = value;
            }
        }

        public string CommercialCardCode
        {
            get
            {
                return this.commercialCardCodeField;
            }
            set
            {
                this.commercialCardCodeField = value;
            }
        }

        public string TransactionMode
        {
            get
            {
                return this.transactionModeField;
            }
            set
            {
                this.transactionModeField = value;
            }
        }

        public string CreditCardTxnType
        {
            get
            {
                return this.creditCardTxnTypeField;
            }
            set
            {
                this.creditCardTxnTypeField = value;
            }
        }
    }

    public partial class SalesReceiptRetCreditCardTxnInfoCreditCardTxnResultInfo
    {

        private int resultCodeField;

        private string resultMessageField;

        private string creditCardTransIDField;

        private string merchantAccountNumberField;

        private string authorizationCodeField;

        private string aVSStreetField;

        private string aVSZipField;

        private string cardSecurityCodeMatchField;

        private string reconBatchIDField;

        private int paymentGroupingCodeField;

        private string paymentStatusField;

        private string txnAuthorizationTimeField;

        private int txnAuthorizationStampField;

        private string clientTransIDField;

        public int ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }

        public string CreditCardTransID
        {
            get
            {
                return this.creditCardTransIDField;
            }
            set
            {
                this.creditCardTransIDField = value;
            }
        }

        public string MerchantAccountNumber
        {
            get
            {
                return this.merchantAccountNumberField;
            }
            set
            {
                this.merchantAccountNumberField = value;
            }
        }

        public string AuthorizationCode
        {
            get
            {
                return this.authorizationCodeField;
            }
            set
            {
                this.authorizationCodeField = value;
            }
        }

        public string AVSStreet
        {
            get
            {
                return this.aVSStreetField;
            }
            set
            {
                this.aVSStreetField = value;
            }
        }

        public string AVSZip
        {
            get
            {
                return this.aVSZipField;
            }
            set
            {
                this.aVSZipField = value;
            }
        }

        public string CardSecurityCodeMatch
        {
            get
            {
                return this.cardSecurityCodeMatchField;
            }
            set
            {
                this.cardSecurityCodeMatchField = value;
            }
        }

        public string ReconBatchID
        {
            get
            {
                return this.reconBatchIDField;
            }
            set
            {
                this.reconBatchIDField = value;
            }
        }

        public int PaymentGroupingCode
        {
            get
            {
                return this.paymentGroupingCodeField;
            }
            set
            {
                this.paymentGroupingCodeField = value;
            }
        }

        public string PaymentStatus
        {
            get
            {
                return this.paymentStatusField;
            }
            set
            {
                this.paymentStatusField = value;
            }
        }

        public string TxnAuthorizationTime
        {
            get
            {
                return this.txnAuthorizationTimeField;
            }
            set
            {
                this.txnAuthorizationTimeField = value;
            }
        }

        public int TxnAuthorizationStamp
        {
            get
            {
                return this.txnAuthorizationStampField;
            }
            set
            {
                this.txnAuthorizationStampField = value;
            }
        }

        public string ClientTransID
        {
            get
            {
                return this.clientTransIDField;
            }
            set
            {
                this.clientTransIDField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineRet
    {

        private string txnLineIDField;

        private SalesReceiptRetSalesReceiptLineRetItemRef itemRefField;

        private string descField;

        private decimal quantityField;

        private string unitOfMeasureField;

        private SalesReceiptRetSalesReceiptLineRetOverrideUOMSetRef overrideUOMSetRefField;

        private string rateField;

        private string ratePercentField;

        private SalesReceiptRetSalesReceiptLineRetClassRef classRefField;

        private decimal amountField;

        private SalesReceiptRetSalesReceiptLineRetInventorySiteRef inventorySiteRefField;

        private SalesReceiptRetSalesReceiptLineRetInventorySiteLocationRef inventorySiteLocationRefField;

        private string serialNumberField;

        private string lotNumberField;

        private string serviceDateField;

        private SalesReceiptRetSalesReceiptLineRetSalesTaxCodeRef salesTaxCodeRefField;

        private string other1Field;

        private string other2Field;

        private SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfo creditCardTxnInfoField;

        private SalesReceiptRetSalesReceiptLineRetDataExtRet dataExtRetField;

        public SalesReceiptRetSalesReceiptLineRet()
        {
            this.dataExtRetField = new SalesReceiptRetSalesReceiptLineRetDataExtRet();
            this.creditCardTxnInfoField = new SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfo();
            this.salesTaxCodeRefField = new SalesReceiptRetSalesReceiptLineRetSalesTaxCodeRef();
            this.inventorySiteLocationRefField = new SalesReceiptRetSalesReceiptLineRetInventorySiteLocationRef();
            this.inventorySiteRefField = new SalesReceiptRetSalesReceiptLineRetInventorySiteRef();
            this.classRefField = new SalesReceiptRetSalesReceiptLineRetClassRef();
            this.overrideUOMSetRefField = new SalesReceiptRetSalesReceiptLineRetOverrideUOMSetRef();
            this.itemRefField = new SalesReceiptRetSalesReceiptLineRetItemRef();
        }

        public string TxnLineID
        {
            get
            {
                return this.txnLineIDField;
            }
            set
            {
                this.txnLineIDField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineRetItemRef ItemRef
        {
            get
            {
                return this.itemRefField;
            }
            set
            {
                this.itemRefField = value;
            }
        }

        public string Desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }

        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        public string UnitOfMeasure
        {
            get
            {
                return this.unitOfMeasureField;
            }
            set
            {
                this.unitOfMeasureField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineRetOverrideUOMSetRef OverrideUOMSetRef
        {
            get
            {
                return this.overrideUOMSetRefField;
            }
            set
            {
                this.overrideUOMSetRefField = value;
            }
        }

        public string Rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }

        public string RatePercent
        {
            get
            {
                return this.ratePercentField;
            }
            set
            {
                this.ratePercentField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineRetClassRef ClassRef
        {
            get
            {
                return this.classRefField;
            }
            set
            {
                this.classRefField = value;
            }
        }

        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineRetInventorySiteRef InventorySiteRef
        {
            get
            {
                return this.inventorySiteRefField;
            }
            set
            {
                this.inventorySiteRefField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineRetInventorySiteLocationRef InventorySiteLocationRef
        {
            get
            {
                return this.inventorySiteLocationRefField;
            }
            set
            {
                this.inventorySiteLocationRefField = value;
            }
        }

        public string SerialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }

        public string LotNumber
        {
            get
            {
                return this.lotNumberField;
            }
            set
            {
                this.lotNumberField = value;
            }
        }

        public string ServiceDate
        {
            get
            {
                return this.serviceDateField;
            }
            set
            {
                this.serviceDateField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineRetSalesTaxCodeRef SalesTaxCodeRef
        {
            get
            {
                return this.salesTaxCodeRefField;
            }
            set
            {
                this.salesTaxCodeRefField = value;
            }
        }

        public string Other1
        {
            get
            {
                return this.other1Field;
            }
            set
            {
                this.other1Field = value;
            }
        }

        public string Other2
        {
            get
            {
                return this.other2Field;
            }
            set
            {
                this.other2Field = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfo CreditCardTxnInfo
        {
            get
            {
                return this.creditCardTxnInfoField;
            }
            set
            {
                this.creditCardTxnInfoField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineRetDataExtRet DataExtRet
        {
            get
            {
                return this.dataExtRetField;
            }
            set
            {
                this.dataExtRetField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineRetItemRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineRetOverrideUOMSetRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineRetClassRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineRetInventorySiteRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineRetInventorySiteLocationRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineRetSalesTaxCodeRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfo
    {

        private SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnInputInfo creditCardTxnInputInfoField;

        private SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnResultInfo creditCardTxnResultInfoField;

        public SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfo()
        {
            this.creditCardTxnResultInfoField = new SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnResultInfo();
            this.creditCardTxnInputInfoField = new SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnInputInfo();
        }

        public SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnInputInfo CreditCardTxnInputInfo
        {
            get
            {
                return this.creditCardTxnInputInfoField;
            }
            set
            {
                this.creditCardTxnInputInfoField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnResultInfo CreditCardTxnResultInfo
        {
            get
            {
                return this.creditCardTxnResultInfoField;
            }
            set
            {
                this.creditCardTxnResultInfoField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnInputInfo
    {

        private string creditCardNumberField;

        private int expirationMonthField;

        private int expirationYearField;

        private string nameOnCardField;

        private string creditCardAddressField;

        private string creditCardPostalCodeField;

        private string commercialCardCodeField;

        private string transactionModeField;

        private string creditCardTxnTypeField;

        public string CreditCardNumber
        {
            get
            {
                return this.creditCardNumberField;
            }
            set
            {
                this.creditCardNumberField = value;
            }
        }

        public int ExpirationMonth
        {
            get
            {
                return this.expirationMonthField;
            }
            set
            {
                this.expirationMonthField = value;
            }
        }

        public int ExpirationYear
        {
            get
            {
                return this.expirationYearField;
            }
            set
            {
                this.expirationYearField = value;
            }
        }

        public string NameOnCard
        {
            get
            {
                return this.nameOnCardField;
            }
            set
            {
                this.nameOnCardField = value;
            }
        }

        public string CreditCardAddress
        {
            get
            {
                return this.creditCardAddressField;
            }
            set
            {
                this.creditCardAddressField = value;
            }
        }

        public string CreditCardPostalCode
        {
            get
            {
                return this.creditCardPostalCodeField;
            }
            set
            {
                this.creditCardPostalCodeField = value;
            }
        }

        public string CommercialCardCode
        {
            get
            {
                return this.commercialCardCodeField;
            }
            set
            {
                this.commercialCardCodeField = value;
            }
        }

        public string TransactionMode
        {
            get
            {
                return this.transactionModeField;
            }
            set
            {
                this.transactionModeField = value;
            }
        }

        public string CreditCardTxnType
        {
            get
            {
                return this.creditCardTxnTypeField;
            }
            set
            {
                this.creditCardTxnTypeField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnResultInfo
    {

        private int resultCodeField;

        private string resultMessageField;

        private string creditCardTransIDField;

        private string merchantAccountNumberField;

        private string authorizationCodeField;

        private string aVSStreetField;

        private string aVSZipField;

        private string cardSecurityCodeMatchField;

        private string reconBatchIDField;

        private int paymentGroupingCodeField;

        private string paymentStatusField;

        private string txnAuthorizationTimeField;

        private int txnAuthorizationStampField;

        private string clientTransIDField;

        public int ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }

        public string CreditCardTransID
        {
            get
            {
                return this.creditCardTransIDField;
            }
            set
            {
                this.creditCardTransIDField = value;
            }
        }

        public string MerchantAccountNumber
        {
            get
            {
                return this.merchantAccountNumberField;
            }
            set
            {
                this.merchantAccountNumberField = value;
            }
        }

        public string AuthorizationCode
        {
            get
            {
                return this.authorizationCodeField;
            }
            set
            {
                this.authorizationCodeField = value;
            }
        }

        public string AVSStreet
        {
            get
            {
                return this.aVSStreetField;
            }
            set
            {
                this.aVSStreetField = value;
            }
        }

        public string AVSZip
        {
            get
            {
                return this.aVSZipField;
            }
            set
            {
                this.aVSZipField = value;
            }
        }

        public string CardSecurityCodeMatch
        {
            get
            {
                return this.cardSecurityCodeMatchField;
            }
            set
            {
                this.cardSecurityCodeMatchField = value;
            }
        }

        public string ReconBatchID
        {
            get
            {
                return this.reconBatchIDField;
            }
            set
            {
                this.reconBatchIDField = value;
            }
        }

        public int PaymentGroupingCode
        {
            get
            {
                return this.paymentGroupingCodeField;
            }
            set
            {
                this.paymentGroupingCodeField = value;
            }
        }

        public string PaymentStatus
        {
            get
            {
                return this.paymentStatusField;
            }
            set
            {
                this.paymentStatusField = value;
            }
        }

        public string TxnAuthorizationTime
        {
            get
            {
                return this.txnAuthorizationTimeField;
            }
            set
            {
                this.txnAuthorizationTimeField = value;
            }
        }

        public int TxnAuthorizationStamp
        {
            get
            {
                return this.txnAuthorizationStampField;
            }
            set
            {
                this.txnAuthorizationStampField = value;
            }
        }

        public string ClientTransID
        {
            get
            {
                return this.clientTransIDField;
            }
            set
            {
                this.clientTransIDField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineRetDataExtRet
    {

        private string ownerIDField;

        private string dataExtNameField;

        private string dataExtTypeField;

        private string dataExtValueField;

        public string OwnerID
        {
            get
            {
                return this.ownerIDField;
            }
            set
            {
                this.ownerIDField = value;
            }
        }

        public string DataExtName
        {
            get
            {
                return this.dataExtNameField;
            }
            set
            {
                this.dataExtNameField = value;
            }
        }

        public string DataExtType
        {
            get
            {
                return this.dataExtTypeField;
            }
            set
            {
                this.dataExtTypeField = value;
            }
        }

        public string DataExtValue
        {
            get
            {
                return this.dataExtValueField;
            }
            set
            {
                this.dataExtValueField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRet
    {

        private string txnLineIDField;

        private SalesReceiptRetSalesReceiptLineGroupRetItemGroupRef itemGroupRefField;

        private string descField;

        private decimal quantityField;

        private string unitOfMeasureField;

        private SalesReceiptRetSalesReceiptLineGroupRetOverrideUOMSetRef overrideUOMSetRefField;

        private bool isPrintItemsInGroupField;

        private decimal totalAmountField;

        private SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRet salesReceiptLineRetField;

        private SalesReceiptRetSalesReceiptLineGroupRetDataExtRet dataExtRetField;

        public SalesReceiptRetSalesReceiptLineGroupRet()
        {
            this.dataExtRetField = new SalesReceiptRetSalesReceiptLineGroupRetDataExtRet();
            this.salesReceiptLineRetField = new SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRet();
            this.overrideUOMSetRefField = new SalesReceiptRetSalesReceiptLineGroupRetOverrideUOMSetRef();
            this.itemGroupRefField = new SalesReceiptRetSalesReceiptLineGroupRetItemGroupRef();
        }

        public string TxnLineID
        {
            get
            {
                return this.txnLineIDField;
            }
            set
            {
                this.txnLineIDField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetItemGroupRef ItemGroupRef
        {
            get
            {
                return this.itemGroupRefField;
            }
            set
            {
                this.itemGroupRefField = value;
            }
        }

        public string Desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }

        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        public string UnitOfMeasure
        {
            get
            {
                return this.unitOfMeasureField;
            }
            set
            {
                this.unitOfMeasureField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetOverrideUOMSetRef OverrideUOMSetRef
        {
            get
            {
                return this.overrideUOMSetRefField;
            }
            set
            {
                this.overrideUOMSetRefField = value;
            }
        }

        public bool IsPrintItemsInGroup
        {
            get
            {
                return this.isPrintItemsInGroupField;
            }
            set
            {
                this.isPrintItemsInGroupField = value;
            }
        }

        public decimal TotalAmount
        {
            get
            {
                return this.totalAmountField;
            }
            set
            {
                this.totalAmountField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRet SalesReceiptLineRet
        {
            get
            {
                return this.salesReceiptLineRetField;
            }
            set
            {
                this.salesReceiptLineRetField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetDataExtRet DataExtRet
        {
            get
            {
                return this.dataExtRetField;
            }
            set
            {
                this.dataExtRetField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetItemGroupRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetOverrideUOMSetRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRet
    {

        private string txnLineIDField;

        private SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetItemRef itemRefField;

        private string descField;

        private decimal quantityField;

        private string unitOfMeasureField;

        private SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetOverrideUOMSetRef overrideUOMSetRefField;

        private string rateField;

        private string ratePercentField;

        private SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetClassRef classRefField;

        private decimal amountField;

        private SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetInventorySiteRef inventorySiteRefField;

        private SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetInventorySiteLocationRef inventorySiteLocationRefField;

        private string serialNumberField;

        private string lotNumberField;

        private string serviceDateField;

        private SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetSalesTaxCodeRef salesTaxCodeRefField;

        private string other1Field;

        private string other2Field;

        private SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfo creditCardTxnInfoField;

        private SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetDataExtRet dataExtRetField;

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRet()
        {
            this.dataExtRetField = new SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetDataExtRet();
            this.creditCardTxnInfoField = new SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfo();
            this.salesTaxCodeRefField = new SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetSalesTaxCodeRef();
            this.inventorySiteLocationRefField = new SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetInventorySiteLocationRef();
            this.inventorySiteRefField = new SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetInventorySiteRef();
            this.classRefField = new SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetClassRef();
            this.overrideUOMSetRefField = new SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetOverrideUOMSetRef();
            this.itemRefField = new SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetItemRef();
        }

        public string TxnLineID
        {
            get
            {
                return this.txnLineIDField;
            }
            set
            {
                this.txnLineIDField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetItemRef ItemRef
        {
            get
            {
                return this.itemRefField;
            }
            set
            {
                this.itemRefField = value;
            }
        }

        public string Desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }

        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        public string UnitOfMeasure
        {
            get
            {
                return this.unitOfMeasureField;
            }
            set
            {
                this.unitOfMeasureField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetOverrideUOMSetRef OverrideUOMSetRef
        {
            get
            {
                return this.overrideUOMSetRefField;
            }
            set
            {
                this.overrideUOMSetRefField = value;
            }
        }

        public string Rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }

        public string RatePercent
        {
            get
            {
                return this.ratePercentField;
            }
            set
            {
                this.ratePercentField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetClassRef ClassRef
        {
            get
            {
                return this.classRefField;
            }
            set
            {
                this.classRefField = value;
            }
        }

        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetInventorySiteRef InventorySiteRef
        {
            get
            {
                return this.inventorySiteRefField;
            }
            set
            {
                this.inventorySiteRefField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetInventorySiteLocationRef InventorySiteLocationRef
        {
            get
            {
                return this.inventorySiteLocationRefField;
            }
            set
            {
                this.inventorySiteLocationRefField = value;
            }
        }

        public string SerialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }

        public string LotNumber
        {
            get
            {
                return this.lotNumberField;
            }
            set
            {
                this.lotNumberField = value;
            }
        }

        public string ServiceDate
        {
            get
            {
                return this.serviceDateField;
            }
            set
            {
                this.serviceDateField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetSalesTaxCodeRef SalesTaxCodeRef
        {
            get
            {
                return this.salesTaxCodeRefField;
            }
            set
            {
                this.salesTaxCodeRefField = value;
            }
        }

        public string Other1
        {
            get
            {
                return this.other1Field;
            }
            set
            {
                this.other1Field = value;
            }
        }

        public string Other2
        {
            get
            {
                return this.other2Field;
            }
            set
            {
                this.other2Field = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfo CreditCardTxnInfo
        {
            get
            {
                return this.creditCardTxnInfoField;
            }
            set
            {
                this.creditCardTxnInfoField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetDataExtRet DataExtRet
        {
            get
            {
                return this.dataExtRetField;
            }
            set
            {
                this.dataExtRetField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetItemRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetOverrideUOMSetRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetClassRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetInventorySiteRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetInventorySiteLocationRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetSalesTaxCodeRef
    {

        private string listIDField;

        private string fullNameField;

        public string ListID
        {
            get
            {
                return this.listIDField;
            }
            set
            {
                this.listIDField = value;
            }
        }

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfo
    {

        private SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnInputInfo creditCardTxnInputInfoField;

        private SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnResultInfo creditCardTxnResultInfoField;

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfo()
        {
            this.creditCardTxnResultInfoField = new SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnResultInfo();
            this.creditCardTxnInputInfoField = new SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnInputInfo();
        }

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnInputInfo CreditCardTxnInputInfo
        {
            get
            {
                return this.creditCardTxnInputInfoField;
            }
            set
            {
                this.creditCardTxnInputInfoField = value;
            }
        }

        public SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnResultInfo CreditCardTxnResultInfo
        {
            get
            {
                return this.creditCardTxnResultInfoField;
            }
            set
            {
                this.creditCardTxnResultInfoField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnInputInfo
    {

        private string creditCardNumberField;

        private int expirationMonthField;

        private int expirationYearField;

        private string nameOnCardField;

        private string creditCardAddressField;

        private string creditCardPostalCodeField;

        private string commercialCardCodeField;

        private string transactionModeField;

        private string creditCardTxnTypeField;

        public string CreditCardNumber
        {
            get
            {
                return this.creditCardNumberField;
            }
            set
            {
                this.creditCardNumberField = value;
            }
        }

        public int ExpirationMonth
        {
            get
            {
                return this.expirationMonthField;
            }
            set
            {
                this.expirationMonthField = value;
            }
        }

        public int ExpirationYear
        {
            get
            {
                return this.expirationYearField;
            }
            set
            {
                this.expirationYearField = value;
            }
        }

        public string NameOnCard
        {
            get
            {
                return this.nameOnCardField;
            }
            set
            {
                this.nameOnCardField = value;
            }
        }

        public string CreditCardAddress
        {
            get
            {
                return this.creditCardAddressField;
            }
            set
            {
                this.creditCardAddressField = value;
            }
        }

        public string CreditCardPostalCode
        {
            get
            {
                return this.creditCardPostalCodeField;
            }
            set
            {
                this.creditCardPostalCodeField = value;
            }
        }

        public string CommercialCardCode
        {
            get
            {
                return this.commercialCardCodeField;
            }
            set
            {
                this.commercialCardCodeField = value;
            }
        }

        public string TransactionMode
        {
            get
            {
                return this.transactionModeField;
            }
            set
            {
                this.transactionModeField = value;
            }
        }

        public string CreditCardTxnType
        {
            get
            {
                return this.creditCardTxnTypeField;
            }
            set
            {
                this.creditCardTxnTypeField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetCreditCardTxnInfoCreditCardTxnResultInfo
    {

        private int resultCodeField;

        private string resultMessageField;

        private string creditCardTransIDField;

        private string merchantAccountNumberField;

        private string authorizationCodeField;

        private string aVSStreetField;

        private string aVSZipField;

        private string cardSecurityCodeMatchField;

        private string reconBatchIDField;

        private int paymentGroupingCodeField;

        private string paymentStatusField;

        private string txnAuthorizationTimeField;

        private int txnAuthorizationStampField;

        private string clientTransIDField;

        public int ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        public string ResultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                this.resultMessageField = value;
            }
        }

        public string CreditCardTransID
        {
            get
            {
                return this.creditCardTransIDField;
            }
            set
            {
                this.creditCardTransIDField = value;
            }
        }

        public string MerchantAccountNumber
        {
            get
            {
                return this.merchantAccountNumberField;
            }
            set
            {
                this.merchantAccountNumberField = value;
            }
        }

        public string AuthorizationCode
        {
            get
            {
                return this.authorizationCodeField;
            }
            set
            {
                this.authorizationCodeField = value;
            }
        }

        public string AVSStreet
        {
            get
            {
                return this.aVSStreetField;
            }
            set
            {
                this.aVSStreetField = value;
            }
        }

        public string AVSZip
        {
            get
            {
                return this.aVSZipField;
            }
            set
            {
                this.aVSZipField = value;
            }
        }

        public string CardSecurityCodeMatch
        {
            get
            {
                return this.cardSecurityCodeMatchField;
            }
            set
            {
                this.cardSecurityCodeMatchField = value;
            }
        }

        public string ReconBatchID
        {
            get
            {
                return this.reconBatchIDField;
            }
            set
            {
                this.reconBatchIDField = value;
            }
        }

        public int PaymentGroupingCode
        {
            get
            {
                return this.paymentGroupingCodeField;
            }
            set
            {
                this.paymentGroupingCodeField = value;
            }
        }

        public string PaymentStatus
        {
            get
            {
                return this.paymentStatusField;
            }
            set
            {
                this.paymentStatusField = value;
            }
        }

        public string TxnAuthorizationTime
        {
            get
            {
                return this.txnAuthorizationTimeField;
            }
            set
            {
                this.txnAuthorizationTimeField = value;
            }
        }

        public int TxnAuthorizationStamp
        {
            get
            {
                return this.txnAuthorizationStampField;
            }
            set
            {
                this.txnAuthorizationStampField = value;
            }
        }

        public string ClientTransID
        {
            get
            {
                return this.clientTransIDField;
            }
            set
            {
                this.clientTransIDField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetSalesReceiptLineRetDataExtRet
    {

        private string ownerIDField;

        private string dataExtNameField;

        private string dataExtTypeField;

        private string dataExtValueField;

        public string OwnerID
        {
            get
            {
                return this.ownerIDField;
            }
            set
            {
                this.ownerIDField = value;
            }
        }

        public string DataExtName
        {
            get
            {
                return this.dataExtNameField;
            }
            set
            {
                this.dataExtNameField = value;
            }
        }

        public string DataExtType
        {
            get
            {
                return this.dataExtTypeField;
            }
            set
            {
                this.dataExtTypeField = value;
            }
        }

        public string DataExtValue
        {
            get
            {
                return this.dataExtValueField;
            }
            set
            {
                this.dataExtValueField = value;
            }
        }
    }

    public partial class SalesReceiptRetSalesReceiptLineGroupRetDataExtRet
    {

        private string ownerIDField;

        private string dataExtNameField;

        private string dataExtTypeField;

        private string dataExtValueField;

        public string OwnerID
        {
            get
            {
                return this.ownerIDField;
            }
            set
            {
                this.ownerIDField = value;
            }
        }

        public string DataExtName
        {
            get
            {
                return this.dataExtNameField;
            }
            set
            {
                this.dataExtNameField = value;
            }
        }

        public string DataExtType
        {
            get
            {
                return this.dataExtTypeField;
            }
            set
            {
                this.dataExtTypeField = value;
            }
        }

        public string DataExtValue
        {
            get
            {
                return this.dataExtValueField;
            }
            set
            {
                this.dataExtValueField = value;
            }
        }
    }

    public partial class SalesReceiptRetDataExtRet
    {

        private string ownerIDField;

        private string dataExtNameField;

        private string dataExtTypeField;

        private string dataExtValueField;

        public string OwnerID
        {
            get
            {
                return this.ownerIDField;
            }
            set
            {
                this.ownerIDField = value;
            }
        }

        public string DataExtName
        {
            get
            {
                return this.dataExtNameField;
            }
            set
            {
                this.dataExtNameField = value;
            }
        }

        public string DataExtType
        {
            get
            {
                return this.dataExtTypeField;
            }
            set
            {
                this.dataExtTypeField = value;
            }
        }

        public string DataExtValue
        {
            get
            {
                return this.dataExtValueField;
            }
            set
            {
                this.dataExtValueField = value;
            }
        }
    }
}
